spring:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailgun.org
    username: dmaster@sandbox04fd135c834e497e8338b89a56b92f5d.mailgun.org
jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false
chirp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false
  web-socket:
    allowed-origin: "http://localhost:8080"
logging:
  level:
    com.dmb.chirp: DEBUG